### ISSUE TITLE
URGENT bug fix

### ISSUE THREAD

**Issue by TJB4epam** [EPAM-Online-Courses/tetris#49]
Without those two being brought back I can't merge ANY PRs.

## Top priority

We lost the ability to run the game

```
Error: LinkageError occurred while loading main class com.epam.prejap.tetris.Tetris
java.lang.UnsupportedClassVersionError: Preview features are not enabled for com/epam/prejap/tetris/Tetris (class file version 58.65535). Try running with '--enable-preview'
```
I'd say that JAR needs to be reconfigured to pass enable preview when running. So one needs to look at the pom.

## Tests not executed when building?

Not all tests seem to be called during build - I don't see the tests using colours for one, that Dominik has introduced.

**Comment by Norbert098** [comment]
Not sure if this is the solution but seems like after changing project SDK on 14 version everything works just fine. 
Well, at least we can run the game.

**Comment by TJB4epam** [comment]
Try doing a PR then! 

Test part was at least partially fixed by #51

**Comment by lukaszspyra** [comment]
I did not found option to configure jar-plugin with --enable-preview, so it must be run manually like java -jar --enable-preview tetris.jar.

**Comment by TJB4epam** [comment]
Usually I'd say - please add this to readme - but for time's sake I'll do it.

Norbert - not really: cause on JDK version 14.0.1 I had the error after making sure POM sets the Java version to 14 - removing enable-preview makes it worse:
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project tetris: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/tammo/tmp/Tetris/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Preview features are not enabled for com/epam/prejap/tetris/block/BlockFeedTest (class file version 58.65535). Try running with '--enable-preview'
```

Therefore - going with Łukasz' option.
